apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aesir-agent.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aesir-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AESIR_TOKEN: {{ required "aesir.token is required" .Values.aesir.token | quote }}

