apiVersion: v1
kind: Service
metadata:
  name: {{ include "aesir-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aesir-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aesir-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: opamp
      port: {{ .Values.opamp.port }}
      targetPort: opamp
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.logs.enabled }}
    - name: logs
      port: {{ .Values.logs.port }}
      targetPort: logs
      protocol: TCP
    {{- end }}
    {{- if .Values.capture.enabled }}
    - name: capture
      port: {{ .Values.capture.port }}
      targetPort: capture
      protocol: TCP
    {{- end }}
